            - name: Claude Assisted Code Review
  # You may pin to the exact commit or the version.
  # uses: arpitgandhi9/creview@5df9b1c954021e16d99bfc8f483d5d175f1645f0
  uses: arpitgandhi9/creview@v0.3
  with:
    # github token
    github_token: 
    # Anthropic API key
    anthropic_api_key: 
    # Claude model name
    model_name: # optional, default is claude-3-5-sonnet-20241022
    # Claude model temperature
    model_temperature: # optional, default is 0
    # Provide a wildcard expression to exclude files from code review. For example, `*.md` will exclude all markdown files. Multiple expressions are supported via commas, eg `*.js, *.cjs`
    exclude_files: # optional, default is 
          
