name: Render Weekday Market Patterns Report

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'  # Every Monday at 06:00 UTC

jobs:
  render:
    name: Build and Deploy Report
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: '1.4.550'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev \
            libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev \
            libjpeg-dev pandoc

      - name: Install required R packages
        run: |
          Rscript -e 'install.packages(c("quantmod", "tidyverse", "plotly", "DT", "lubridate", "scales", "httr", "jsonlite", "rmarkdown"))'

      - name: Attempt data fetch (non-fatal)
        run: |
          Rscript -e 'tryCatch(source("scripts/fetch_data.R"), error = function(e) message("⚠️ fetch_data.R failed: ", e$message))'

      - name: Render Quarto report to HTML
        run: |
          quarto render weekday-market-patterns.qmd --to html
        continue-on-error: false

      - name: Upload rendered HTML as artifact
        uses: actions/upload-artifact@v4
        with:
          name: weekday-market-patterns-report
          path: weekday-market-patterns.html

      # Optional GitHub Pages deployment
      # Uncomment below if you want automatic publishing to gh-pages
      #
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./_site
