name: Generate Market Patterns Report

on:
  schedule:
    - cron: '0 0 1 1,7 *'  # Runs Jan 1 and July 1 at midnight UTC
  workflow_dispatch:
    inputs:
      generate_html:
        description: 'Generate HTML version'
        required: false
        default: true
        type: boolean

env:
  QUARTO_VERSION: "1.5.36"
  R_VERSION: "4.3.3"
  OUTPUT_DIR: "reports"
  CACHE_DIR: ".cache"
  MIN_TRADING_DAYS: 1000
  MIN_WEEKDAY_COUNT: 100
  DATA_DIR: "data"  # Directory for cached financial data

jobs:
  generate-report:
    name: Generate Report
    runs-on: ubuntu-latest
    timeout-minutes: 90
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      # -------- INITIAL SETUP --------
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # -------- SYSTEM DEPENDENCIES --------
      - name: Install system packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
            libcurl4-openssl-dev libssl-dev libxml2-dev \
            libfontconfig1-dev libharfbuzz-dev libfribidi-dev \
            libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev \
            pandoc git-lfs ca-certificates \
            texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra

      # -------- TOOL INSTALLATION --------
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ env.R_VERSION }}
          use-public-rspm: true

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: ${{ env.QUARTO_VERSION }}
          tinytex: true
          install-tinytex: true

      # -------- CACHE SETUP --------
      - name: Cache R packages
        uses: actions/cache@v4
        id: r-cache
        with:
          path: |
            ~/.local/share/renv
            ~/R/library
            ${{ env.CACHE_DIR }}/R
          key: ${{ runner.os }}-r-${{ env.R_VERSION }}-${{ hashFiles('**/renv.lock', '**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-${{ env.R_VERSION }}-

      - name: Cache Quarto
        uses: actions/cache@v4
        id: quarto-cache
        with:
          path: |
            _freeze
            ${{ env.CACHE_DIR }}/quarto
          key: ${{ runner.os }}-quarto-${{ env.QUARTO_VERSION }}-${{ hashFiles('**/*.qmd', '**/*.Rmd') }}
          restore-keys: |
            ${{ runner.os }}-quarto-${{ env.QUARTO_VERSION }}-

      - name: Cache financial data
        uses: actions/cache@v4
        id: data-cache
        with:
          path: |
            ${{ env.DATA_DIR }}/
          key: ${{ runner.os }}-data-${{ hashFiles('**/*.csv', '**/*.json') }}
          restore-keys: |
            ${{ runner.os }}-data-

      # -------- PACKAGE INSTALLATION --------
      - name: Install R dependencies
        run: |
          mkdir -p ${{ env.CACHE_DIR }}/R ${{ env.CACHE_DIR }}/quarto
          Rscript -e '
          options(repos = c(CRAN = "https://cloud.r-project.org"))
          core_pkgs <- c("renv", "pak", "devtools")
          install.packages(core_pkgs)
          
          if (file.exists("renv.lock")) {
            renv::restore(confirm = FALSE)
          } else {
            req_pkgs <- c(
              "tidyverse", "lubridate", "plotly", "quantmod", "tidyquant",
              "httr", "jsonlite", "rvest", "xml2", "TTR", "curl", "DT",
              "rmarkdown", "knitr", "kableExtra", "here", "fs"
            )
            if (requireNamespace("pak", quietly = TRUE)) {
              pak::pkg_install(req_pkgs, ask = FALSE)
            } else {
              install.packages(req_pkgs)
            }
          }
          '

      # -------- REPORT GENERATION --------
      - name: Create output directory
        run: mkdir -p ${{ env.OUTPUT_DIR }}

      - name: Render HTML report
        id: render-html
        run: |
          quarto render Weekday_Market_Patterns.qmd \
            --to html \
            --output-dir ${{ env.OUTPUT_DIR }} \
            --cache \
            --fail-on-warning
        continue-on-error: true

      - name: Retry failed HTML render
        if: steps.render-html.outcome == 'failure'
        run: |
          quarto render Weekday_Market_Patterns.qmd \
            --to html \
            --output-dir ${{ env.OUTPUT_DIR }} \
            --no-cache

      # -------- OUTPUT HANDLING --------
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: market-patterns-report-${{ github.run_number }}
          path: |
            ${{ env.OUTPUT_DIR }}/
            package_report.csv
          retention-days: 90

      - name: Deploy to GitHub Pages
        if: success() && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.OUTPUT_DIR }}/
          keep_files: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'docs: Update market patterns report [skip ci]'

      # -------- VERSION CONTROL --------
      - name: Commit results
        if: success() && github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          
          git add ${{ env.OUTPUT_DIR }}/*.html
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: Auto-update market report [skip ci]"
            git pull --rebase
            git push origin HEAD:main
          fi

      # -------- NOTIFICATIONS --------
      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ Report generation failed! See run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
            })
