name: Generate Weekly Market Patterns Report

on:
  schedule:
    # Run every Monday at 00:00 UTC
    - cron: '0 0 * * 1'
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev pandoc libfontconfig1-dev libfreetype6-dev pkg-config
      
      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("rmarkdown", "tidyverse", "lubridate", "plotly", "DT", "knitr", "quantmod", "tidyquant", "stringr", "htmltools", "htmlwidgets", "scales"), repos = "https://cloud.r-project.org")'
      
      - name: Generate weekday market patterns report
        run: |
          Rscript -e 'rmarkdown::render("weekday-market-patterns.qmd", output_file = "weekday-market-patterns.html")'
      
      - name: Commit and push if there are changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add weekday-market-patterns.html
          git diff --quiet && git diff --staged --quiet || git commit -m "Update weekly market patterns report [automated]"
          git push
